@startuml

frame it.jnrpe.engine {
    package services.events {
        () IEventManager
        () IEventType
        IEventManager ..> IEventType : use
        [LogEvent] -> IEventType
    }

    package services.config {
        () IConfigProvider
        () IConfigSource
        IConfigProvider ..> IConfigSource : uses
    }

    package services.network {
        () INetworkListener
    }

    package services.plugins {
        () IPlugin
        () IPluginRepository
        IPluginRepository ..> IPlugin : uses
    }
}

frame it.jnrpe.services.events {
    [ConsoleEventManager] --> IEventManager
}

frame it.jnrpe.services.config {
    [IniJnrpeConfigProvider] ---> IConfigProvider
    [XmlJnrpeConfigProvider] ---> IConfigProvider
    [YamlJnrpeConfigProvider] ---> IConfigProvider
}

frame it.jnrpe.services.network.netty {
    [JnrpeNettyListenerService] --> INetworkListener
}

frame it.jnrpe.services.plugin {
    [JavaServicePluginRepository] --> IPluginRepository
}

frame it.jnrpe.services.plugins {
    [CheckDiskPlugin] -> IPlugin
    [CheckMemoryPlugin] -> IPlugin
}

@enduml
