name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Check Style
        run: ./gradlew spotlessCheck
      - name: Build
        run: ./gradlew build -x test -x spotlessCheck -x spotbugsTest -x spotbugsMain -x javadoc
      - name: Run Static Analysis
        run: ./gradlew spotbugsMain spotbugsTest
      - name: Run tests
        run: ./gradlew test
      - name: Coveralls
        uses: coverallsapp/github-action@v2
