name: Publish Daily Snapshot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check_release:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check_git_commits.release == 0}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: check_git_commits
        name: Count commits after last tag
        run: |
          echo "::set-output name=release::$(git rev-list `git describe --abbrev=0`..HEAD --count)"
  build:
    needs: check_release
    if: needs.check_release.outputs.status == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - id: check_snapshot
        name: Check SNAPSHOT status
        run: |
          echo "::set-output name=version::$(git rev-list `git describe --abbrev=0`..HEAD --count)"
      - name: Build with Gradle
        if: ${{ steps.check_snapshot.outputs.version == 0}}
        run: ./gradlew build
      - name: Publish Snapshot to Central Repository
        if: ${{ steps.check_snapshot.outputs.version == 0}}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSWORD }}
        run: ./gradlew publish
