name: Publish Daily Snapshot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check_snapshot:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check_git_commits.outputs.release != 0}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: check_git_commits
        name: Count commits after last tag
        run: |
          echo "::set-output name=release::$(git rev-list `git describe --abbrev=0`..HEAD --count)"
  build:
    needs: check_snapshot
    if: needs.check_snapshot.outputs.status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 'master'
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish Snapshot to Central Repository
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSWORD }}
        run: ./gradlew publish
